apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: otus
  name: webapplication1-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapplication1-service
                port:
                  number: 80
                